export const ENDPOINT = {
  API: {
    REGISTER_USER: '/api/auth/signup',
    LOGIN_USER: '/api/auth/login',
    FORGOT_PASSWORD: '/api/auth/password/forget',
    RESET_PASSWORD_USER: '/api/auth/password/recovery',
    GET_MY_PROFILE: '/api/profile/get',
    UPDATE_MY_PROFILE: '/api/profile/update',
    CHANGE_PASSWORD_USER: '/api/auth/password/change',
    ADD_PRODUCT_API: '/api/product/addProduct',
  },
  ROUTING: {
    AUTH: '/auth',
    SIGNUP: '/auth/register',
    LOGIN: '/auth/login',
    LOGIN_WITH_GOOGLE: '/v1/auth/google',
    LOGIN_SUCCESS: '/login/success',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    RESEND_VERIFY_EMAIL: '/auth/verify-email/resend',
    LOGOUT: '/auth/logout',
    HOME: '/',
    MY_PROFILE: '/my-profile',
    ERROR: '/error',
    ERROR_404: '/error/404',
  },
};
